import type { Metadata } from 'next';
import { montserrat, openSans } from '../../fonts';
import './globals.scss';

import '@rainbow-me/rainbowkit/styles.css';
import Provider from './Provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${openSans.variable} antialiased`}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
