import type { Metadata } from 'next';
import { ToastContainer } from 'react-toastify';

import { montserrat, openSans } from '../../fonts';
import Provider from './Provider';
import 'react-toastify/dist/ReactToastify.css';
import './globals.scss';
import '@rainbow-me/rainbowkit/styles.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${openSans.variable} antialiased`}
      >
        <Provider>
          {children}
          <ToastContainer position="top-center" theme="colored" />
        </Provider>
      </body>
    </html>
  );
}
